Restructure project
- Move all stow packages under stow dir
- Move all path.fish files under fish/.config/fish/paths.fish
  similarly to aliases
- Move install scripts under install dir

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,30 +1,29 @@
 #!/usr/bin/env bash
-#
-# bootstrap installs things.
 
 cd "$(dirname "$0")/.."
 DOTFILES_ROOT=$(pwd)
+STOW_DIR="${DOTFILES_ROOT}/stow"
 
 set -e
 
 echo ''
 
 info () {
-  printf "  [ \033[00;34m..\033[0m ] $1"
+    printf "  [ \033[00;34m..\033[0m ] $1"
 }
 
 user () {
-  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+    printf "\r  [ \033[0;33m?\033[0m ] $1 "
 }
 
 success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
 }
 
 fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+    echo ''
+    exit
 }
 
 require_util () {
@@ -37,44 +36,45 @@ check_requirements () {
 }
 
 setup_gitconfig () {
-  if ! [ -f git.stow/.gitconfig ]
-  then
-    info 'setup gitconfig'
-
-    git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
+    if ! [[ -f "${STOW_DIR}/git/.gitconfig" ]]
     then
-      git_credential='osxkeychain'
-    fi
+        info 'setup gitconfig'
 
-    user ' - What is your github author name?'
-    read -e git_authorname
-    user ' - What is your github author email?'
-    read -e git_authoremail
+        GIT_CREDENTIAL='cache'
+        if [[ "$(uname -s)" == "Darwin" ]]
+        then
+          GIT_CREDENTIAL='osxkeychain'
+        fi
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" \
-      -e "s/AUTHOREMAIL/$git_authoremail/g" \
-      -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" \
-      git.stow/.gitconfig.template > git.stow/.gitconfig
+        user ' - What is your github author name?'
+        read -e GIT_AUTHOR_NAME
+        user ' - What is your github author email?'
+        read -e GIT_AUTHOR_EMAIL
+
+        sed -e "s/AUTHORNAME/${GIT_AUTHOR_NAME}/g" \
+        -e "s/AUTHOREMAIL/${GIT_AUTHOR_EMAIL}/g" \
+        -e "s/GIT_CREDENTIAL_HELPER/${GIT_CREDENTIAL}/g" \
+      "${STOW_DIR}/git/.gitconfig.template" > "${STOW_DIR}/git/.gitconfig"
 
     success 'gitconfig'
   fi
 }
 
 link_stow () {
-  local src="${1}"
-  local package="$(basename ${src})"
-  stow -d "${DOTFILES_ROOT}" -t "${HOME}" -S "${package}" || fail "failed to stow ${src}"
-  success "stowed ${src}"
+    local SRC="${1}"
+    local DIR="$(dirname ${SRC})"
+    local PACKAGE="$(basename ${SRC})"
+    stow -d "${DIR}" -t "${HOME}" -S "${PACKAGE}" || fail "failed to stow ${SRC}"
+    success "stowed ${SRC}"
 }
 
 
 install_dotfiles () {
     info 'installing dotfiles'
 
-    for src in $(find "${DOTFILES_ROOT}" -maxdepth 2 -name '*.stow')
+    for SRC in $(find "${STOW_DIR}" -maxdepth 1 -type d)
     do
-      link_stow "${src}"
+      link_stow "${SRC}"
     done
 }
 
